import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from '@/components/Footer/Footer'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
const data = new Date().getFullYear()

  return (
    <html lang="en">
      <body className='flex flex-col justify-start gap-4 p-20 items-center min-h-screen'>
        
        <header className="flex flex-col items-center">
          <h1>React & Next.js</h1>
          <nav className="flex gap-4">
            <a href="/">Intro</a>
            <a href="/sobre">Sobre</a>
            <a href="/caracteristicas">Caracteristicas</a>
            <a href="/tecnologias">Tecnologias</a>
            <a href="/projetos">Projetos</a>
            <a href="/contador">Contador</a>
            <a href="/input">Input</a>
            <a href="/produtos">Produtos</a>
            <a href="/categorias">Categorias</a>
          </nav>
        </header>
        
        <main className="bg-blue-200 p-5 rounded-2xl max-w-2xl min-h-[70vh]">
          {children}
        </main>
        
        <Footer />

      </body>
    </html>
  );
}
